# Generated by Django 4.1.7 on 2023-03-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptoprequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='user_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('S', 'Student'), ('T', 'Teacher')], default='A', max_length=1),
        ),
    ]
