# Generated by Django 4.1.7 on 2023-03-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptoprequest', '0002_newuser_user_id_alter_newuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'ordering': ['role']},
        ),
    ]
