# Generated by Django 4.1.7 on 2023-03-15 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptoprequest', '0003_alter_newuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=7)),
                ('os', models.CharField(choices=[('A', 'MacOS'), ('W', 'Windows')], default='W', max_length=1)),
                ('ram', models.CharField(choices=[('S', '16GB'), ('H', '64GB')], default='S', max_length=1)),
                ('ssd', models.CharField(choices=[('S', '512GB'), ('H', '4TB')], default='S', max_length=1)),
                ('graphic_card', models.CharField(choices=[('S', '4GB'), ('H', '12GB')], default='S', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Available'), ('U', 'Unavailable'), ('N', 'Non Operational'), ('R', 'Retired')], default='A', max_length=1)),
                ('computer_classification', models.CharField(choices=[('S', 'Standard'), ('H', 'High Performance')], default='S', max_length=1)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('C', 'Created'), ('P', 'Pending'), ('F', 'Finalized'), ('R', 'Rejected')], default='C', max_length=1)),
                ('student_email', models.EmailField(max_length=254)),
                ('teacher_email', models.EmailField(max_length=254)),
                ('computer_sn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laptoprequest.computer')),
            ],
        ),
    ]
