# Generated by Django 4.1.7 on 2023-03-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptoprequest', '0005_alter_newuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer_classification',
            field=models.CharField(choices=[('Standard', 'Standard'), ('High Performance', 'High Performance')], default='Standard', max_length=17),
        ),
        migrations.AlterField(
            model_name='computer',
            name='graphic_card',
            field=models.CharField(choices=[('Standard', '4GB'), ('High Performance', '12GB')], default='Standard', max_length=17),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os',
            field=models.CharField(choices=[('MacOS', 'MacOS'), ('Windows', 'Windows')], default='Windows', max_length=17),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.CharField(choices=[('Standard', '16GB'), ('High Performance', '64GB')], default='Standard', max_length=17),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ssd',
            field=models.CharField(choices=[('Standard', '512GB'), ('High Performance', '4TB')], default='Standard', max_length=17),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Non Operational', 'Non Operational'), ('Retired', 'Retired')], default='Available', max_length=17),
        ),
        migrations.AlterField(
            model_name='request',
            name='order_status',
            field=models.CharField(choices=[('Created', 'Created'), ('Pending', 'Pending'), ('Finalized', 'Finalized'), ('Rejected', 'Rejected')], default='Created', max_length=10),
        ),
    ]
