# Generated by Django 4.1.7 on 2023-03-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptoprequest', '0006_alter_computer_computer_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='student_f_n',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='student_l_n',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='teacher_f_n',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='teacher_l_n',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
