# Generated by Django 4.1.7 on 2023-03-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptoprequest', '0008_rename_student_f_n_request_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
