# Generated by Django 4.1.7 on 2023-03-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptoprequest', '0009_request_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='request',
            name='computer_classification',
            field=models.CharField(choices=[('Standard', 'Standard'), ('High Performance', 'High Performance')], default='Standard', max_length=17),
        ),
        migrations.AddField(
            model_name='request',
            name='os',
            field=models.CharField(choices=[('MacOS', 'MacOS'), ('Windows', 'Windows')], default='Windows', max_length=17),
        ),
    ]
