# Generated by Django 4.1.7 on 2023-03-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptoprequest', '0010_request_approved_request_computer_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
