# Generated by Django 4.1.7 on 2023-03-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptoprequest', '0011_request_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='approved_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
