# Generated by Django 4.1.7 on 2023-03-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptoprequest', '0012_alter_request_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer_classification',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Performance', 'Performance')], default='Standard', max_length=17),
        ),
        migrations.AlterField(
            model_name='computer',
            name='graphic_card',
            field=models.CharField(choices=[('Standard', '4GB'), ('Performance', '12GB')], default='Standard', max_length=17),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.CharField(choices=[('Standard', '16GB'), ('Performance', '64GB')], default='Standard', max_length=17),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ssd',
            field=models.CharField(choices=[('Standard', '512GB'), ('Performance', '4TB')], default='Standard', max_length=17),
        ),
        migrations.AlterField(
            model_name='request',
            name='computer_classification',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Performance', 'Performance')], default='Standard', max_length=17),
        ),
    ]
