# Generated by Django 4.1.7 on 2023-03-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptoprequest', '0014_request_returned_request_returned_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='order_status',
            field=models.CharField(choices=[('Created', 'Created'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Denied', 'Denied'), ('Ready', 'Ready'), ('Check Out', 'Check Out'), ('Returned', 'Returned')], default='Created', max_length=10),
        ),
    ]
