# Generated by Django 4.1.7 on 2023-04-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptoprequest', '0015_alter_request_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='graphic_card',
            field=models.CharField(choices=[('4GB', '4GB'), ('12GB', '12GB')], default='4GB', max_length=17),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.CharField(choices=[('16GB', '16GB'), ('64GB', '64GB')], default='16GB', max_length=17),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ssd',
            field=models.CharField(choices=[('512GB', '512GB'), ('4TB', '4TB')], default='512GB', max_length=17),
        ),
    ]
