# Generated by Django 4.2 on 2023-04-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptoprequest', '0016_alter_computer_graphic_card_alter_computer_ram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='order_status',
            field=models.CharField(choices=[('Created', 'Created'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Denied', 'Denied'), ('Ready', 'Ready'), ('Checked Out', 'Checked Out'), ('Returned', 'Returned')], default='Created', max_length=15),
        ),
    ]
